#crng28:
datadir: "./data/LCG28_24.dat"
savedir: "./model/LCG28_big.model"
nbits: 8
seqlen: 20
seed: 42
train_split: 0.97
total_split: 1
train_size: 10000000000
batch_size: 1024
test_iter: 10000
num_workers: 32
model_type: 'gopher-44m'
name: 'LCG28_24_gopher'
logdir: "./logs/"