#crng32:
datadir: "./data/LCG32_24.dat"
savedir: "./model/LCG32.model"
nbits: 8
seqlen: 20
seed: 42
train_split: 0.97
total_split: 1
train_size: 10000000000
batch_size: 4096
test_iter: 10000
num_workers: 32
model_type: 'gpt-mini'
name: 'LCG32_24'
logdir: "./logs/"