#crng28:
datadir: "./data/LCG28_24.dat"
savedir: "./model/LCG28_noncausal_lr_1e-3.model"
nbits: 8
seqlen: 20
seed: 42
train_split: 0.97
total_split: 1
train_size: 10000000000
batch_size: 4196
test_iter: 10000
num_workers: 32
learning_rate: 1e-3
model_type: 'gpt-mini'
causal: false
name: 'LCG28_24_non_causal_lr1e-3'
logdir: "./logs/"