#68G:
datadir: "/data/2023-10-23-QRNG-DATA/rng-data/prenoise/500M/3.homodyne_on/output.dat"
savedir: "./model/prenoise500M_homodyneon.model"
nbits: 16
seqlen: 20
seed: 42
train_split: 0.97
total_split: 1
train_size: 10000000000
batch_size: 1024
test_iter: 10000
num_workers: 32
causal: true
model_type: 'gpt-mini'
name: 'prenoise500M_homodyneon'
logdir: "./logs/"