#68G:
datadir: "/data/2023-10-23-QRNG-DATA/rng-data/Thermal noice/mergeddata1_500M.dat"
savedir: "./model/thermal.model"
nbits: 8
seqlen: 20
seed: 42
train_split: 0.97
total_split: 1
train_size: 10000000000
batch_size: 1024
test_iter: 10000
num_workers: 32
model_type: 'gpt-mini'
name: 'thermal'
logdir: "./logs/"